Repository CapituloJaverianoACM/WebSiteAPI, pull requests merged in 2020-07, with the labels that each got.

#44 Update /dev dependencies
  requirements.txt
Labels: dependencies

#47 whitelist updated
  acm_web_site/settings.py
Labels: bug

#39 Feature/36 GitHub actions
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  acm_web_site/settings.py
Labels: enhancement

#51 Feature/45 fix bare execpts
  web_site/api/email_service.py
  web_site/api/member_service.py
  web_site/urls.py
  web_site/views.py
Labels: bug

#49 Initial folder organization
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/tests.yml
  acm_web_site/apps/__init__.py
  acm_web_site/apps/business/__init__.py
  acm_web_site/apps/business/web_site/__init__.py
  acm_web_site/apps/business/web_site/admin.py
  acm_web_site/apps/business/web_site/api/__init__.py
  acm_web_site/apps/business/web_site/api/activity_service.py
  acm_web_site/apps/business/web_site/api/award_service.py
  acm_web_site/apps/business/web_site/api/email_service.py
  acm_web_site/apps/business/web_site/api/member_service.py
  acm_web_site/apps/business/web_site/api/project_service.py
  acm_web_site/apps/business/web_site/api/team_service.py
  acm_web_site/apps/business/web_site/api/tutorial_service.py
  acm_web_site/apps/business/web_site/apps.py
  acm_web_site/apps/business/web_site/forms.py
  acm_web_site/apps/business/web_site/migrations/0001_initial.py
  acm_web_site/apps/business/web_site/migrations/__init__.py
  acm_web_site/apps/business/web_site/models.py
  acm_web_site/apps/business/web_site/serializer/__init__.py
  acm_web_site/apps/business/web_site/serializer/activity_serializer.py
  acm_web_site/apps/business/web_site/serializer/award_serializer.py
  acm_web_site/apps/business/web_site/serializer/gallery_serializer.py
  acm_web_site/apps/business/web_site/serializer/member_serializer.py
  acm_web_site/apps/business/web_site/serializer/project_serializer.py
  acm_web_site/apps/business/web_site/serializer/team_serializer.py
  acm_web_site/apps/business/web_site/serializer/tutorial_serializer.py
  acm_web_site/apps/business/web_site/tests.py
  acm_web_site/apps/business/web_site/urls.py
  acm_web_site/apps/business/web_site/views.py
  acm_web_site/apps/utils/__init__.py
  acm_web_site/manage.py
  acm_web_site/settings.py
  acm_web_site/settings/__init__.py
  acm_web_site/settings/common.py
  acm_web_site/settings/development.py
  acm_web_site/urls.py
  acm_web_site/wsgi.py
  package.json
  requirements.txt
  requirements/common.txt
  requirements/development.txt
  tox.ini
  web_site/models.py
Labels: bug, enhancement

#53 Configured urls in business folder.
  acm_web_site/apps/business/urls.py
  acm_web_site/urls.py
Labels: enhancement

#57 Information app
  acm_web_site/apps/business/information/__init__.py
  acm_web_site/apps/business/information/admin.py
  acm_web_site/apps/business/information/apps.py
  acm_web_site/apps/business/information/forms.py
  acm_web_site/apps/business/information/migrations/0001_initial.py
  acm_web_site/apps/business/information/migrations/__init__.py
  acm_web_site/apps/business/information/models.py
  acm_web_site/apps/business/information/serializers.py
  acm_web_site/apps/business/information/services.py
  acm_web_site/apps/business/information/tests/__init__.py
  acm_web_site/apps/business/information/urls.py
  acm_web_site/apps/business/information/views.py
  acm_web_site/apps/business/urls.py
  acm_web_site/apps/business/web_site/admin.py
  acm_web_site/apps/business/web_site/api/award_service.py
  acm_web_site/apps/business/web_site/api/email_service.py
  acm_web_site/apps/business/web_site/api/member_service.py
  acm_web_site/apps/business/web_site/forms.py
  acm_web_site/apps/business/web_site/migrations/0002_auto_20200721_0136.py
  acm_web_site/apps/business/web_site/models.py
  acm_web_site/apps/business/web_site/serializer/award_serializer.py
  acm_web_site/apps/business/web_site/urls.py
  acm_web_site/apps/business/web_site/views.py
  acm_web_site/settings/common.py
Labels: enhancement

#66 Move settings folder
  .github/workflows/tests.yml
  acm_web_site/acm_web_site/__init__.py
  acm_web_site/acm_web_site/settings/__init__.py
  acm_web_site/acm_web_site/settings/common.py
  acm_web_site/acm_web_site/settings/development.py
  acm_web_site/acm_web_site/urls.py
  acm_web_site/acm_web_site/wsgi.py
  acm_web_site/apps/business/activities/migrations/0002_auto_20200726_0854.py
  acm_web_site/apps/business/activities/urls.py
  acm_web_site/apps/business/information/migrations/0002_delete_member.py
  acm_web_site/apps/business/information/urls.py
  acm_web_site/apps/business/people/urls.py
  acm_web_site/apps/business/urls.py
  acm_web_site/manage.py
Labels: enhancement

#61 Feature/60 update utils
  acm_web_site/acm_web_site/settings/common.py
  acm_web_site/apps/business/activities/admin.py
  acm_web_site/apps/business/activities/migrations/0002_auto_20200723_1405.py
  acm_web_site/apps/business/activities/serializers.py
  acm_web_site/apps/business/information/admin.py
  acm_web_site/apps/business/information/serializers.py
  acm_web_site/apps/business/people/admin.py
  acm_web_site/apps/business/people/serializers.py
  acm_web_site/apps/utils/utils.py
Labels: enhancement

#72 Addressed TODOs
  acm_web_site/apps/business/activities/serializers.py
  acm_web_site/apps/business/activities/urls.py
  acm_web_site/apps/business/activities/views.py
  acm_web_site/apps/business/information/admin.py
  acm_web_site/apps/business/information/serializers.py
  acm_web_site/apps/business/information/urls.py
  acm_web_site/apps/business/people/services.py
  acm_web_site/apps/business/people/urls.py
  acm_web_site/apps/business/people/views.py
Labels: enhancement

#74 Feature/73 activity detail todos
  acm_web_site/apps/business/activities/serializers.py
  acm_web_site/apps/business/activities/services.py
  acm_web_site/apps/business/activities/views.py
Labels: bug, enhancement
